
exports.rArray1 = [
 { "vlcn":"1", "name":"Sir Robert Russell ", "status":"unknown" },
 { "vlcn":"2", "name":"Thomas Andrews ", "status":"unknown" } ];

exports.rArray2 = [
 { "vlcn":"3", "name":"Eme Knightly ", "status":"unknown" },
 { "vlcn":"4", "name":"Sir George Throckmorton ", "status":"unknown" },
 { "vlcn":"5", "name":"Katherine Throckmorton ", "status":"unknown" },
 { "vlcn":"6", "name":"Lady in Lace ", "status":"unknown" },
 { "vlcn":"7F", "name":"Kneeling Knight ", "status":"unknown" },
 { "vlcn":"8", "name":"Sons of John Harewell ", "status":"unknown" },
 { "vlcn":"9 ", "name":"Sons of John Harewell ", "status":"unknown" },
 { "vlcn":"10", "name":"Standing Monk", "status":"unknown" },
 { "vlcn":"11", "name":"Robert Chambers ", "status":"unknown" },
 { "vlcn":"12", "name":"Knight, standing, lion at feet", "status":"unknown" },
 { "vlcn":"13", "name":"Centre of England", "status":"unknown" },
 { "vlcn":"14", "name":"Rise Griffyn", "status":"unknown" },
 { "vlcn":"15", "name":"Gentleman", "status":"unknown" },
 { "vlcn":"16", "name":"Kneeling Knight, to right", "status":"unknown" },
 { "vlcn":"17", "name":"Two small angelic emblems", "status":"unknown" },
 { "vlcn":"18", "name":"Bishop, holding Chalice", "status":"unknown" },
 { "vlcn":"19", "name":"Coughton Court Children ", "status":"unknown" },
 { "vlcn":"20", "name":"Man and Woman", "status":"unknown" },
 { "vlcn":"21", "name":"William Abell ", "status":"unknown" },
 { "vlcn":"22", "name":"Bearded Saint", "status":"unknown" },
 { "vlcn":"23", "name":"Bearded Gentleman", "status":"unknown" },
 { "vlcn":"24", "name":"Robed cleric with inscription", "status":"unknown" },
 { "vlcn":"25", "name":"Seven daughters", "status":"unknown" },
 { "vlcn":"26", "name":"Sir John Bernard and Elena Mallory ", "status":"unknown" },
 { "vlcn":"27", "name":"Five small scrolled inscriptions", "status":"unknown" },
 { "vlcn":"28", "name":"Long Inscription, Sub...", "status":"unknown" },
 { "vlcn":"29", "name":"Man and Wife", "status":"unknown" },
 { "vlcn":"30", "name":"Knight and Wife", "status":"unknown" },
 { "vlcn":"31", "name":"Margaret Francis Peyton ", "status":"unknown" },
 { "vlcn":"32", "name":"Lady in Lace ", "status":"unknown" },
 { "vlcn":"33", "name":"Thomas Peyton ", "status":"unknown" },
 { "vlcn":"34", "name":"Kneeling Knight", "status":"unknown" },
 { "vlcn":"35", "name":"Lady  (Knight, Lady, and Children)", "status":"unknown" },
 { "vlcn":"36", "name":"Knight (Kight, Lady, and Children)", "status":"unknown" },
 { "vlcn":"37", "name":"Children  (Kight, Lady, and Children)", "status":"unknown" },
 { "vlcn":"38", "name":"Kneeling Knight", "status":"unknown" },
 { "vlcn":"39", "name":"Man and Wife", "status":"unknown" },
 { "vlcn":"40", "name":"Knight, with 41", "status":"unknown" },
 { "vlcn":"41", "name":"Lady, with 40", "status":"unknown" },
 { "vlcn":"42", "name":"Sir John Bernard and Elena Mallory", "status":"unknown" },
 { "vlcn":"43", "name":"Andrew Evyngar Family ", "status":"unknown" },
 { "vlcn":"44", "name":"John Fenton, with Bible, and inscription ", "status":"unknown" },
 { "vlcn":"45", "name":"Benedict Medley and Wife ", "status":"unknown" },
 { "vlcn":"46", "name":"Knight, Wife, Sons, Daughters, and Heralds", "status":"unknown" },
 { "vlcn":"47", "name":"Knight and Wife", "status":"unknown" },
 { "vlcn":"48", "name":"Knight and Wife", "status":"unknown" },
 { "vlcn":"49", "name":"Lady", "status":"unknown" },
 { "vlcn":"50", "name":"Centre of England", "status":"unknown" },
 { "vlcn":"51", "name":"Inscription, Sub... Thomas Anrewes...", "status":"unknown" },
 { "vlcn":"52", "name":"Resurrection Brass ", "status":"unknown" },
 { "vlcn":"53", "name":"Angel from Thomas Andrews Arms ", "status":"unknown" },
 { "vlcn":"54", "name":"Angel from Thomas Andrews Arms ", "status":"unknown" },
 { "vlcn":"55", "name":"Thomas Andrews Arms - Helmet, Shield, and Angels ", "status":"unknown" },
 { "vlcn":"56", "name":"Knight (with #57, Wife)", "status":"unknown" },
 { "vlcn":"57", "name":"Wife (with #56, Knight)", "status":"unknown" },
 { "vlcn":"58", "name":"Gentleman", "status":"unknown" },
 { "vlcn":"59", "name":"Sir John Russell and Dame Edith Unton ", "status":"unknown" },
 { "vlcn":"60", "name":"Elizabeth Rotton ", "status":"unknown" },
 { "vlcn":"61", "name":"Elizabeth Rotton ", "status":"unknown" },
 { "vlcn":"62", "name":"Unknown Merchant", "status":"unknown" },
 { "vlcn":"63", "name":"John Walsingham and Elenor", "status":"unknown" },
 { "vlcn":"64", "name":"William Abell", "status":"unknown"  },
 { "vlcn":"65", "name":"Lady", "status":"unknown" },
 { "vlcn":"66", "name":"Rev. Fenton ", "status":"unknown" },
 { "vlcn":"67", "name":"Richard Beresford, arms ", "status":"unknown" },
 { "vlcn":"68", "name":"Thomas Andrews ", "status":"unknown" },
 { "vlcn":"69", "name":"Wool Merchant", "status":"unknown"  },
 { "vlcn":"70", "name":"Kneeling Priest", "status":"unknown" },
 { "vlcn":"71", "name":"Tall Man with Lamb & Pillow", "status":"unknown" },
 { "vlcn":"72", "name":"Thomas Stokes Family ", "status":"unknown" },
 { "vlcn":"73", "name":"Sir Thomas Andrews ", "status":"unknown" },
 { "vlcn":"74", "name":"Wife (of Thomas Andrews) ", "status":"unknown" },
 { "vlcn":"75", "name":"Sir Robert Russell ", "status":"unknown" },
 { "vlcn":"76", "name":"Shrouded Man", "status":"unknown" },
 { "vlcn":"77J", "name":"Knight with two heraldic arms", "status":"unknown" },
 { "vlcn":"78J", "name":"Sons & Daughters of Thomas Andrews ", "status":"unknown" },
 { "vlcn":"79J", "name":"Lady", "status":"unknown" },
 { "vlcn":"80J", "name":"Knight", "status":"unknown" },
 { "vlcn":"81J", "name":"Richard Water and Alice ", "status":"unknown" },
 { "vlcn":"82J", "name":"Thomas Peyton ", "status":"unknown" },
 { "vlcn":"83J", "name":"Lady In Lace ", "status":"unknown" },
 { "vlcn":"84F", "name":"lady", "status":"unknown" },
 { "vlcn":"85F", "name":"man, full hair", "status":"unknown" },
 { "vlcn":"86F", "name":"lady (F84)", "status":"unknown" },
 { "vlcn":"87F", "name":"lady (F84)", "status":"unknown" },
 { "vlcn":"88F", "name":"Praying Knight", "status":"unknown" },
 { "vlcn":"89F", "name":"(taller) Praying Knight", "status":"unknown" },
 { "vlcn":"90F", "name":"(tall) Knight", "status":"unknown" },
 { "vlcn":"91F", "name":"Lady", "status":"unknown" },
 { "vlcn":"92F", "name":"Lady", "status":"unknown" },
 { "vlcn":"93F", "name":"Knight (~F88)", "status":"unknown" },
 { "vlcn":"94F", "name":"Thomas Sexton's Wife ", "status":"unknown" },
 { "vlcn":"95F", "name":"Thomas Sexton", "status":"unknown" },
 { "vlcn":"96F", "name":"Lady, on lamb", "status":"unknown" },
 { "vlcn":"97F", "name":"Abell ? ", "status":"unknown" },
 { "vlcn":"98F", "name":"Shield", "status":"unknown" },
 { "vlcn":"99F", "name":"Four Captions", "status":"unknown" },
 { "vlcn":"100F", "name":"Foot emblem", "status":"unknown" },
 { "vlcn":"101J", "name":"Margaret Francis Peyton ", "status":"unknown" },
 { "vlcn":"102J", "name":"William Smarte ", "status":"unknown" },
 { "vlcn":"103G", "name":"ginny 1", "status":"unknown" },
 { "vlcn":"104G", "name":"ginny 2", "status":"unknown" }
];

exports.rArray3 = [
{ "vlcn":"1", "$set": { "desc":"gold crayon on black paper; cut and mounted on black paper, gold frame. 19-1/2in x 57-1/2in", "location":"RC/basement/boxed" } },
{ "vlcn":"2", "$set": { "desc":"gold crayon on black paper; cut and mounted on black paper, black frame with gold edging. 17in x 46in", "location":"RC/basement/boxed" } }
];

exports.rArray4 = [
{ "vlcn":"3", "$set": { "desc":"gold crayon on black paper; cut and mounted on black paper. black frame with gold edging. 17in x 46in", "location":"RC/basement/boxed" } },
{ "vlcn":"4", "$set": { "desc":"black crayon on white paper; cut and mounted on white paper. black frame with gold edging. 20in x 43in", "location":"RC/basement/boxed" } },
{ "vlcn":"5", "$set": { "desc":"black crayon on white paper; cut and mounted on white paper. black frame with gold edging. 20in x 43in", "location":"RC/basement/boxed" } },
{ "vlcn":"6", "$set": { "desc":"gold crayon on black paper; cut and mounted on gold wallpaper. black frame. 16in x 35in", "location":"RC/dining room" } },
{ "vlcn":"7F", "$set": { "desc":"silver foil inked with black, filled and mounted on green felt on wood boardi. 12in x 22in", "location":"RC/dining room" } },
{ "vlcn":"8", "$set": { "desc":"gold crayon on white paper; 7in x 8in, uncut. w/ #9", "location":"RC/basement/boxed" } },
{ "vlcn":"9", "$set": { "desc":"bronze crayon on white paper; 7in x 8in, uncut. w/ #8", "location":"RC/basement/boxed" } },
{ "vlcn":"10", "$set": { "desc":"silver crayon on black paper; 13in x 16in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"11", "$set": { "desc":"copper crayon on white paper; uncut.", "location":"RC/basement/boxed" } },
{ "vlcn":"12", "$set": { "desc":"copper crayon on black paper;  7in x 23in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"13", "$set": { "desc":"copper crayon on white paper; 11-1/2in square, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"14", "$set": { "desc":"silver crayon on black paper; 10-1/2in x 15in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"15", "$set": { "desc":"gold crayon on black paper; 8in x 18in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"16", "$set": { "desc":"gold crayon on black paper; 12in x 15in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"17", "$set": { "desc":"gold on red/salmon paper; each 4in x 4in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"18", "$set": { "desc":"gold crayon on black paper; 7in x 17in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"19", "$set": { "desc":"black crayon on white paper; 9in x9in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"20", "$set": { "desc":"black crayon on silver textured wall paper; each figure 11in x 4in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"21", "$set": { "desc":"copper crayon on black paper; 13in x 4in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"22", "$set": { "desc":"copper crayon on white; 16in x 5in, uncut", "location":"RC/basement/boxed" } },
{ "vlcn":"23", "$set": { "desc":"gold crayon on black paper", "location":"RC/basement/boxed" } },
{ "vlcn":"24", "$set": { "desc":"gold crayon on black paper; 13in x 15in, uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"25", "$set": { "desc":"gold crayon on black paper; 7in  x 11in", "location": "RC/basement/boxed" } },
{ "vlcn":"26", "$set": { "desc":"Bronze crayon on white paper; Each, 24in x 7in", "location": "RC/basement/boxed" } },
{ "vlcn":"27", "$set": { "desc":"gold crayon on black paper; each 4in x 3in,  uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"28", "$set": { "desc":"black crayon on textured silver wallpaper; 26in x4in  uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"29", "$set": { "desc":"black crayon on textured silver wallpaper; each 25in x7in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"30", "$set": { "desc":"gold crayon on black paper; Knight: 16in x5in , Wife: 15in x 4in", "location": "RC/basement/boxed" } },
{ "vlcn":"31", "$set": { "desc":"gold crayon on black paper; 28in  x 11in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"32", "$set": { "desc":"gold crayon on black paper; 28in  x 12in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"33", "$set": { "desc":"gold crayon on black paper; 28in  x 10in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"34", "$set": { "desc":"silver crayon on thick black paper; 18in  x 9in  uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"35", "$set": { "desc":"black crayon on silver, textured wallpaper; 25in  x 9in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"36", "$set": { "desc":"black crayon on silver, textured wallpaper; 25in  x 9in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"37", "$set": { "desc":"black crayon on silver, textured wallpaper; 10in  x 7in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"38", "$set": { "desc":"black crayon on silver, textured wallpaper; 9in  x 18in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"39", "$set": { "desc":"gold crayon on black paper; each 5in  x 17in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"40", "$set": { "desc":"black crayon on gold, textured wallpaper; 11in  x 35in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"41", "$set": { "desc":"black crayon on gold, textured wallpaper; 11in  x 35in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"42", "$set": { "desc":"gold bronze, on black paper; each 7in  x 24in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"43", "$set": { "desc":"gold crayon on black paper; 23in  x 34in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"44", "$set": { "desc":"black crayon on textured silver wallpaper; 8in  x 19in , with 18in  x 5in  inscription, uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"45", "$set": { "desc":"gold/bronze cayon on black paper; each figure 8in  x 24in , with inscription, 28in  x 5in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"46", "$set": { "desc":"gold crayon on black paper; whole set of brasses: 38in  x 23in; knight and wife, each 8in  x 15in , set of children, each 8in  x 7in , heralds 6in  x 6in", "location": "RC/basement/boxed" } },
{ "vlcn":"47", "$set": { "desc":"gold crayon on black paper; each 5in  x 15in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"48", "$set": { "desc":"gold crayon on black paper; each 5in  x 16in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"49", "$set": { "desc":"gold crayon on black paper; 4in  x 12in , with inscription, 13in  x 3in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"50", "$set": { "desc":"bronze crayon on black paper; 12in  x 12in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"51", "$set": { "desc":"silver crayon on black paper; 26in  x 4in", "location": "RC/basement/boxed" } },
{ "vlcn":"52", "$set": { "desc":"black crayon on textured silver wallpaper; 11in  x 11in , with two separate captions, 8in  x 1-1/2in", "location": "RC/basement/boxed" } },
{ "vlcn":"53", "$set": { "desc":"gold crayon on thick red paper; 6in  x 8in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"54", "$set": { "desc":"gold crayon on white paper; each 6in  x 8in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"55", "$set": { "desc":"gold crayon on black paper; 14in  x 14in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"56", "$set": { "desc":"silver crayon on black paper; 8in  x 25in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"57", "$set": { "desc":"silver crayon on black paper; 7in  x 24in , uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"58", "$set": { "desc":"gold crayon on black paper; 8in x 18in, uncut", "location": "RC/basement/boxed" } },
{ "vlcn":"59", "$set": { "desc":"gold crayon on black paper; 20-1/2in  x 27in , both figures, inscription, and arms", "location": "RC/basement/hanging" } },
{ "vlcn":"60", "$set": { "desc":"black crayon on gold textured paper; 10in  x 27in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"61", "$set": { "desc":"gold crayon on black paper; 10in  x 27in  uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"62", "$set": { "desc":"bronze crayon on black paper; 8in  x 34in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"63", "$set": { "desc":"silver crayon on black paper; figures, 7in  x 23; two arms,  6in  x 6in  each; inscription 19in  x 5in", "location": "RC/basement/hanging" } },
{ "vlcn":"64", "$set": { "desc":"gold crayon on black paper; figure, 4in  x 13in ; inscription, 13in  x 3in", "location": "RC/basement/hanging" } },
{ "vlcn":"65", "$set": { "desc":"black crayon on textured gold paper; 7in  x 27in", "location": "RC/basement/hanging" } },
{ "vlcn":"66", "$set": { "desc":"gold crayon on black paper; figure, 8in  x 19in ; inscription, 18in  x 5in", "location": "RC/basement/hanging" } },
{ "vlcn":"67", "$set": { "desc":"black crayon on gold textured paper; arms, 12in  x 14in ; inscription, 24in  x 10in", "location": "RC/basement/hanging" } },
{ "vlcn":"68", "$set": { "desc":"bronze crayon on white paper; 11in  x 47in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"69", "$set": { "desc":"bronze crayon on white paper; 15in  x 57in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"70", "$set": { "desc":"silver crayon on black paper; 13in  x 29in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"71", "$set": { "desc":"gold crayon on black paper; 12in  x 37in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"72", "$set": { "desc":"gold crayon on black paper; 20in  x 55in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"73", "$set": { "desc":"black crayon on gold textured paper (wallpaper); 11in  x 36in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"74", "$set": { "desc":"black crayon on gold textured paper (wallpaper); 11in  x 36in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"75", "$set": { "desc":"black crayon on silver textured paper (wallpaper); 11in  x 50in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"76", "$set": { "desc":"gold crayon on black, matte, paper; 11in  x 45in , uncut", "location": "RC/basement/hanging" } },
{ "vlcn":"77J", "$set": { "desc":"black crayon on salmon/pink paper; framed, no inscription", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"78J", "$set": { "desc":"gold crayon on black paper; framed, no inscription", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"79J", "$set": { "desc":"gold crayon on black paper; framed, no inscription", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"80J", "$set": { "desc":"gold crayon on black paper; framed, no inscription", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"81J", "$set": { "desc":"copper crayon on white paper; framed, with inscription: Richard Water, 1515, and Alice, his wife / Swaffam Prior, Cambridgeshire, England / Ginny Campbell  1971", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"82J", "$set": { "desc":"black crayon on textured gold paper; Framed; no inscription.", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"83J", "$set": { "desc":"black crayon on gold paper; Framed; no inscription.", "location": "Jody Blackwell/hanging" } },
{ "vlcn":"F84", "$set": { "desc":"copper-colored foil, backed & inked; 5in  x 15in", "location": "RC/basement/boxed" } },
{ "vlcn":"F85", "$set": { "desc":"silver foil, uncut, not inked; 5in  x 17in", "location": "RC/basement/boxed" } },
{ "vlcn":"F86", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 15in", "location": "RC/basement/boxed" } },
{ "vlcn":"F87", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 15in , with some inscription", "location": "RC/basement/boxed" } },
{ "vlcn":"F88", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 16in", "location": "RC/basement/boxed" } },
{ "vlcn":"F89", "$set": { "desc":"silver foil, uncut, backed not inked; 8in  x 25in", "location": "RC/basement/boxed" } },
{ "vlcn":"90F", "$set": { "desc":"silver foil, uncut, backed, not inked; 8in  x 26in", "location": "RC/basement/boxed" } },
{ "vlcn":"91F", "$set": { "desc":"silver foil, uncut, backed, not inked; 9in  x 25in", "location": "RC/basement/boxed" } },
{ "vlcn":"92F", "$set": { "desc":"silver foil, uncut, backed, not inked; 6in  x 16in", "location": "RC/basement/boxed" } },
{ "vlcn":"93F", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 16in", "location": "RC/basement/boxed" } },
{ "vlcn":"94F", "$set": { "desc":"silver foil, uncut, backed, not inked;", "location": "RC/basement/boxed" } },
{ "vlcn":"95F", "$set": { "desc":"silver foil, uncut, backed, not inked; 5in  x 19in", "location": "RC/basement/boxed" } },
{ "vlcn":"96F", "$set": { "desc":"silver foil, uncut, backed not inked; 9in  x 29in", "location": "RC/basement/boxed" } },
{ "vlcn":"97F", "$set": { "desc":"silver foil, uncut, backed, not inked; 6in  x 17in", "location": "RC/basement/boxed" } },
{ "vlcn":"98F", "$set": { "desc":"silver foil, uncut, backed, not inked; 5in  x 6in", "location": "RC/basement/boxed" } },
{ "vlcn":"99F", "$set": { "desc":"copper  foil, uncut, backed, not inked; each 4in  x 2in", "location": "RC/basement/boxed" } },
{ "vlcn":"F100", "$set": { "desc":"silver foil, uncut, backed, not inked; 6in  circle", "location": "RC/basement/boxed" } },
{ "vlcn":"101J", "$set": { "desc":"black crayon on gold paper; Framed; no inscription", "location": "Jody Blackwell/Hanging" } },
{ "vlcn":"102J", "$set": { "desc":"gold crayon on black paper; Framed; no inscription", "location": "Jody Blackwell/Hanging" } }
];

exports.rArray5 = [
{ "vlcn":"9", "$set": { "desc":"bronze crayon on white paper; 7in x 8in, uncut. w/ #8", "location":"RC/basement/boxed" } },
{ "vlcn":"84F", "$set": { "desc":"copper-colored foil, backed & inked; 5in  x 15in", "location": "RC/basement/boxed" } },
{ "vlcn":"85F", "$set": { "desc":"silver foil, uncut, not inked; 5in  x 17in", "location": "RC/basement/boxed" } },
{ "vlcn":"86F", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 15in", "location": "RC/basement/boxed" } },
{ "vlcn":"87F", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 15in , with some inscription", "location": "RC/basement/boxed" } },
{ "vlcn":"88F", "$set": { "desc":"copper foil, uncut, backed, not inked; 5in  x 16in", "location": "RC/basement/boxed" } },
{ "vlcn":"89F", "$set": { "desc":"silver foil, uncut, backed not inked; 8in  x 25in", "location": "RC/basement/boxed" } },
{ "vlcn":"100F", "$set": { "desc":"silver foil, uncut, backed, not inked; 6in  circle", "location": "RC/basement/boxed" } }
];
